In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

In [141]:
X = df.iloc[0:100, [0, 2]].values
y = df.iloc[0:100, 4].values
y = np.where(y == 'Iris-setosa', -1, 1)

In [142]:
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [162]:
class Perceptron(object):
    """Perceptron classifier.

    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.

    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    errors_ : list
      Number of misclassifications (updates) in each epoch.

    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        self.history = []

    def fit(self, X, y):
        """Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_samples, n_features]
          Training vectors, where n_samples is the number of samples and
          n_features is the number of features.
        y : array-like, shape = [n_samples]
          Target values.

        Returns
        -------
        self : object

        """
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        print(self.w_)
        self.errors_ = []
        
        for _ in range(self.n_iter):
            errors = 0
            for xi, target in zip(X, y):
                d = self.predict(xi)
                diff = (target - d)
                update = self.eta * diff
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            print(self.w_)
            self.errors_.append(errors)
        
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)




In [163]:
per = Perceptron(eta=0.01, n_iter=50, random_state=1)
per.fit(X, y)
per.predict(X[0])

[ 0.01624345 -0.00611756 -0.00528172]
[0.03624345 0.13388244 0.08871828]
[0.01624345 0.07388244 0.12671828]
[-0.00375655  0.01988244  0.16271828]
[-0.00375655  0.03188244  0.20471828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07011756  0.17671828]
[-0.02375655 -0.07

array(-1)